// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: APIMTLSTio.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MqGrpcProject {

  /// <summary>Holder for reflection information generated from APIMTLSTio.proto</summary>
  public static partial class APIMTLSTioReflection {

    #region Descriptor
    /// <summary>File descriptor for APIMTLSTio.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static APIMTLSTioReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBBUElNVExTVGlvLnByb3RvEg1NcUdycGNQcm9qZWN0IosCChBBUElNVExT",
            "VF9SZXF1ZXN0EhAKCG10cmxjYXRlGAEgASgJEhUKDW10cmxwcm9kdWN0aWQY",
            "AiABKAkSEQoJbXRybGxvdGlkGAMgASgJEhAKCG10cmxzdGF0GAQgASgJEhYK",
            "Dm10cmxwb3NpdGlvbmlkGAUgASgJEhEKCWNvbmVxcHRpZBgGIAEoCRISCgpz",
            "YWxlc29yZGVyGAcgASgJEg4KBmxpbmVpZBgIIAEoCRISCgpjcmVhdGVkYXRl",
            "GAkgASgJEg0KBWxvdGlkGAogASgJEg8KB254b3Blbm8YCyABKAkSFAoMcXVl",
            "cnlzdWJtdHJsGAwgASgJEhAKCHNlcnZlcmlwGA0gASgJItgBCg5BUElNVExT",
            "VF9SZXBseRINCgV0cnhpZBgBIAEoCRIOCgZ0eXBlaWQYAiABKAkSDwoHcnRu",
            "Y29kZRgDIAEoCRIPCgdydG5tZXNnGAQgASgJEg8KB210cmxjbnQYBSABKAkS",
            "KAoEb2FyeRgGIAMoCzIaLk1xR3JwY1Byb2plY3QuQVBJTVRMU1RvX2ESDgoG",
            "bWFzY250GAcgASgJEioKBW9hcnkyGAggAygLMhsuTXFHcnBjUHJvamVjdC5B",
            "UElNVExTVG9fYTISDgoGZXJybXNnGAkgASgJIu4DCgtBUElNVExTVG9fYRIV",
            "Cg1tdHJscHJvZHVjdGlkGAEgASgJEhEKCW10cmxsb3RpZBgCIAEoCRINCgVz",
            "ZXFubxgDIAEoCRITCgtjb250YWluZXJpZBgEIAEoCRIQCghtdHJsY2F0ZRgF",
            "IAEoCRIQCghtdHJsc3RhdBgGIAEoCRIPCgdtdHJscXR5GAcgASgJEg8KB2No",
            "Z2RhdGUYCCABKAkSDwoHY2hndGltZRgJIAEoCRIPCgdjaGd1c2VyGAogASgJ",
            "EhEKCXRhcmVxcHRpZBgLIAEoCRIOCgZlcXB0aWQYDCABKAkSDwoHZXFwdG10",
            "ZxgNIAEoCRIPCgdjb21tZW50GA4gASgJEhUKDW1za3Bvc2l0aW9uaWQYDyAB",
            "KAkSFwoPZGF0YXJlcGRhdGV0aW1lGBAgASgJEg4KBm9vc2ZsZxgRIAEoCRIS",
            "CgpjcmVhdGVkYXRlGBIgASgJEhIKCmV4cGlyZWRhdGUYEyABKAkSEwoLdmFs",
            "aWRwZXJpb2QYFCABKAkSEQoJbWludXNlcXR5GBUgASgJEhIKCnNhbGVzb3Jk",
            "ZXIYFiABKAkSDgoGbGluZWlkGBcgASgJEhEKCWVub3VnaGZsZxgYIAEoCRIN",
            "CgVsb3RpZBgZIAEoCRIOCgZzaGVldHMYGiABKAkifwoMQVBJTVRMU1RvX2Ey",
            "EhIKCm10cmxwcm9kaWQYASABKAkSFQoNc3VibXRybHByb2RpZBgCIAEoCRIS",
            "Cgpwcm9wb3J0aW9uGAMgASgJEg4KBnVzZXJpZBgEIAEoCRIPCgdjaGdkYXRl",
            "GAUgASgJEg8KB2NoZ3RpbWUYBiABKAlCMwoVaW8uZ3JwYy5NcUdycGNQcm9q",
            "ZWN0QhJNcUdycGNQcm9qZWN0UHJvdG9QAaICA0hMV2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MqGrpcProject.APIMTLST_Request), global::MqGrpcProject.APIMTLST_Request.Parser, new[]{ "Mtrlcate", "Mtrlproductid", "Mtrllotid", "Mtrlstat", "Mtrlpositionid", "Coneqptid", "Salesorder", "Lineid", "Createdate", "Lotid", "Nxopeno", "Querysubmtrl", "Serverip" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MqGrpcProject.APIMTLST_Reply), global::MqGrpcProject.APIMTLST_Reply.Parser, new[]{ "Trxid", "Typeid", "Rtncode", "Rtnmesg", "Mtrlcnt", "Oary", "Mascnt", "Oary2", "Errmsg" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MqGrpcProject.APIMTLSTo_a), global::MqGrpcProject.APIMTLSTo_a.Parser, new[]{ "Mtrlproductid", "Mtrllotid", "Seqno", "Containerid", "Mtrlcate", "Mtrlstat", "Mtrlqty", "Chgdate", "Chgtime", "Chguser", "Tareqptid", "Eqptid", "Eqptmtg", "Comment", "Mskpositionid", "Datarepdatetime", "Oosflg", "Createdate", "Expiredate", "Validperiod", "Minuseqty", "Salesorder", "Lineid", "Enoughflg", "Lotid", "Sheets" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MqGrpcProject.APIMTLSTo_a2), global::MqGrpcProject.APIMTLSTo_a2.Parser, new[]{ "Mtrlprodid", "Submtrlprodid", "Proportion", "Userid", "Chgdate", "Chgtime" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class APIMTLST_Request : pb::IMessage<APIMTLST_Request> {
    private static readonly pb::MessageParser<APIMTLST_Request> _parser = new pb::MessageParser<APIMTLST_Request>(() => new APIMTLST_Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<APIMTLST_Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MqGrpcProject.APIMTLSTioReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIMTLST_Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIMTLST_Request(APIMTLST_Request other) : this() {
      mtrlcate_ = other.mtrlcate_;
      mtrlproductid_ = other.mtrlproductid_;
      mtrllotid_ = other.mtrllotid_;
      mtrlstat_ = other.mtrlstat_;
      mtrlpositionid_ = other.mtrlpositionid_;
      coneqptid_ = other.coneqptid_;
      salesorder_ = other.salesorder_;
      lineid_ = other.lineid_;
      createdate_ = other.createdate_;
      lotid_ = other.lotid_;
      nxopeno_ = other.nxopeno_;
      querysubmtrl_ = other.querysubmtrl_;
      serverip_ = other.serverip_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIMTLST_Request Clone() {
      return new APIMTLST_Request(this);
    }

    /// <summary>Field number for the "mtrlcate" field.</summary>
    public const int MtrlcateFieldNumber = 1;
    private string mtrlcate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mtrlcate {
      get { return mtrlcate_; }
      set {
        mtrlcate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mtrlproductid" field.</summary>
    public const int MtrlproductidFieldNumber = 2;
    private string mtrlproductid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mtrlproductid {
      get { return mtrlproductid_; }
      set {
        mtrlproductid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mtrllotid" field.</summary>
    public const int MtrllotidFieldNumber = 3;
    private string mtrllotid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mtrllotid {
      get { return mtrllotid_; }
      set {
        mtrllotid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mtrlstat" field.</summary>
    public const int MtrlstatFieldNumber = 4;
    private string mtrlstat_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mtrlstat {
      get { return mtrlstat_; }
      set {
        mtrlstat_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mtrlpositionid" field.</summary>
    public const int MtrlpositionidFieldNumber = 5;
    private string mtrlpositionid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mtrlpositionid {
      get { return mtrlpositionid_; }
      set {
        mtrlpositionid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "coneqptid" field.</summary>
    public const int ConeqptidFieldNumber = 6;
    private string coneqptid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Coneqptid {
      get { return coneqptid_; }
      set {
        coneqptid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "salesorder" field.</summary>
    public const int SalesorderFieldNumber = 7;
    private string salesorder_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Salesorder {
      get { return salesorder_; }
      set {
        salesorder_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lineid" field.</summary>
    public const int LineidFieldNumber = 8;
    private string lineid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Lineid {
      get { return lineid_; }
      set {
        lineid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "createdate" field.</summary>
    public const int CreatedateFieldNumber = 9;
    private string createdate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Createdate {
      get { return createdate_; }
      set {
        createdate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lotid" field.</summary>
    public const int LotidFieldNumber = 10;
    private string lotid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Lotid {
      get { return lotid_; }
      set {
        lotid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nxopeno" field.</summary>
    public const int NxopenoFieldNumber = 11;
    private string nxopeno_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Nxopeno {
      get { return nxopeno_; }
      set {
        nxopeno_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "querysubmtrl" field.</summary>
    public const int QuerysubmtrlFieldNumber = 12;
    private string querysubmtrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Querysubmtrl {
      get { return querysubmtrl_; }
      set {
        querysubmtrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "serverip" field.</summary>
    public const int ServeripFieldNumber = 13;
    private string serverip_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Serverip {
      get { return serverip_; }
      set {
        serverip_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as APIMTLST_Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(APIMTLST_Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Mtrlcate != other.Mtrlcate) return false;
      if (Mtrlproductid != other.Mtrlproductid) return false;
      if (Mtrllotid != other.Mtrllotid) return false;
      if (Mtrlstat != other.Mtrlstat) return false;
      if (Mtrlpositionid != other.Mtrlpositionid) return false;
      if (Coneqptid != other.Coneqptid) return false;
      if (Salesorder != other.Salesorder) return false;
      if (Lineid != other.Lineid) return false;
      if (Createdate != other.Createdate) return false;
      if (Lotid != other.Lotid) return false;
      if (Nxopeno != other.Nxopeno) return false;
      if (Querysubmtrl != other.Querysubmtrl) return false;
      if (Serverip != other.Serverip) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Mtrlcate.Length != 0) hash ^= Mtrlcate.GetHashCode();
      if (Mtrlproductid.Length != 0) hash ^= Mtrlproductid.GetHashCode();
      if (Mtrllotid.Length != 0) hash ^= Mtrllotid.GetHashCode();
      if (Mtrlstat.Length != 0) hash ^= Mtrlstat.GetHashCode();
      if (Mtrlpositionid.Length != 0) hash ^= Mtrlpositionid.GetHashCode();
      if (Coneqptid.Length != 0) hash ^= Coneqptid.GetHashCode();
      if (Salesorder.Length != 0) hash ^= Salesorder.GetHashCode();
      if (Lineid.Length != 0) hash ^= Lineid.GetHashCode();
      if (Createdate.Length != 0) hash ^= Createdate.GetHashCode();
      if (Lotid.Length != 0) hash ^= Lotid.GetHashCode();
      if (Nxopeno.Length != 0) hash ^= Nxopeno.GetHashCode();
      if (Querysubmtrl.Length != 0) hash ^= Querysubmtrl.GetHashCode();
      if (Serverip.Length != 0) hash ^= Serverip.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Mtrlcate.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Mtrlcate);
      }
      if (Mtrlproductid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Mtrlproductid);
      }
      if (Mtrllotid.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Mtrllotid);
      }
      if (Mtrlstat.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Mtrlstat);
      }
      if (Mtrlpositionid.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Mtrlpositionid);
      }
      if (Coneqptid.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Coneqptid);
      }
      if (Salesorder.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Salesorder);
      }
      if (Lineid.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Lineid);
      }
      if (Createdate.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Createdate);
      }
      if (Lotid.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Lotid);
      }
      if (Nxopeno.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Nxopeno);
      }
      if (Querysubmtrl.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Querysubmtrl);
      }
      if (Serverip.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Serverip);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Mtrlcate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mtrlcate);
      }
      if (Mtrlproductid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mtrlproductid);
      }
      if (Mtrllotid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mtrllotid);
      }
      if (Mtrlstat.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mtrlstat);
      }
      if (Mtrlpositionid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mtrlpositionid);
      }
      if (Coneqptid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Coneqptid);
      }
      if (Salesorder.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Salesorder);
      }
      if (Lineid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Lineid);
      }
      if (Createdate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Createdate);
      }
      if (Lotid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Lotid);
      }
      if (Nxopeno.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nxopeno);
      }
      if (Querysubmtrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Querysubmtrl);
      }
      if (Serverip.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Serverip);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(APIMTLST_Request other) {
      if (other == null) {
        return;
      }
      if (other.Mtrlcate.Length != 0) {
        Mtrlcate = other.Mtrlcate;
      }
      if (other.Mtrlproductid.Length != 0) {
        Mtrlproductid = other.Mtrlproductid;
      }
      if (other.Mtrllotid.Length != 0) {
        Mtrllotid = other.Mtrllotid;
      }
      if (other.Mtrlstat.Length != 0) {
        Mtrlstat = other.Mtrlstat;
      }
      if (other.Mtrlpositionid.Length != 0) {
        Mtrlpositionid = other.Mtrlpositionid;
      }
      if (other.Coneqptid.Length != 0) {
        Coneqptid = other.Coneqptid;
      }
      if (other.Salesorder.Length != 0) {
        Salesorder = other.Salesorder;
      }
      if (other.Lineid.Length != 0) {
        Lineid = other.Lineid;
      }
      if (other.Createdate.Length != 0) {
        Createdate = other.Createdate;
      }
      if (other.Lotid.Length != 0) {
        Lotid = other.Lotid;
      }
      if (other.Nxopeno.Length != 0) {
        Nxopeno = other.Nxopeno;
      }
      if (other.Querysubmtrl.Length != 0) {
        Querysubmtrl = other.Querysubmtrl;
      }
      if (other.Serverip.Length != 0) {
        Serverip = other.Serverip;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Mtrlcate = input.ReadString();
            break;
          }
          case 18: {
            Mtrlproductid = input.ReadString();
            break;
          }
          case 26: {
            Mtrllotid = input.ReadString();
            break;
          }
          case 34: {
            Mtrlstat = input.ReadString();
            break;
          }
          case 42: {
            Mtrlpositionid = input.ReadString();
            break;
          }
          case 50: {
            Coneqptid = input.ReadString();
            break;
          }
          case 58: {
            Salesorder = input.ReadString();
            break;
          }
          case 66: {
            Lineid = input.ReadString();
            break;
          }
          case 74: {
            Createdate = input.ReadString();
            break;
          }
          case 82: {
            Lotid = input.ReadString();
            break;
          }
          case 90: {
            Nxopeno = input.ReadString();
            break;
          }
          case 98: {
            Querysubmtrl = input.ReadString();
            break;
          }
          case 106: {
            Serverip = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class APIMTLST_Reply : pb::IMessage<APIMTLST_Reply> {
    private static readonly pb::MessageParser<APIMTLST_Reply> _parser = new pb::MessageParser<APIMTLST_Reply>(() => new APIMTLST_Reply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<APIMTLST_Reply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MqGrpcProject.APIMTLSTioReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIMTLST_Reply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIMTLST_Reply(APIMTLST_Reply other) : this() {
      trxid_ = other.trxid_;
      typeid_ = other.typeid_;
      rtncode_ = other.rtncode_;
      rtnmesg_ = other.rtnmesg_;
      mtrlcnt_ = other.mtrlcnt_;
      oary_ = other.oary_.Clone();
      mascnt_ = other.mascnt_;
      oary2_ = other.oary2_.Clone();
      errmsg_ = other.errmsg_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIMTLST_Reply Clone() {
      return new APIMTLST_Reply(this);
    }

    /// <summary>Field number for the "trxid" field.</summary>
    public const int TrxidFieldNumber = 1;
    private string trxid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Trxid {
      get { return trxid_; }
      set {
        trxid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "typeid" field.</summary>
    public const int TypeidFieldNumber = 2;
    private string typeid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Typeid {
      get { return typeid_; }
      set {
        typeid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "rtncode" field.</summary>
    public const int RtncodeFieldNumber = 3;
    private string rtncode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Rtncode {
      get { return rtncode_; }
      set {
        rtncode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "rtnmesg" field.</summary>
    public const int RtnmesgFieldNumber = 4;
    private string rtnmesg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Rtnmesg {
      get { return rtnmesg_; }
      set {
        rtnmesg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mtrlcnt" field.</summary>
    public const int MtrlcntFieldNumber = 5;
    private string mtrlcnt_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mtrlcnt {
      get { return mtrlcnt_; }
      set {
        mtrlcnt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "oary" field.</summary>
    public const int OaryFieldNumber = 6;
    private static readonly pb::FieldCodec<global::MqGrpcProject.APIMTLSTo_a> _repeated_oary_codec
        = pb::FieldCodec.ForMessage(50, global::MqGrpcProject.APIMTLSTo_a.Parser);
    private readonly pbc::RepeatedField<global::MqGrpcProject.APIMTLSTo_a> oary_ = new pbc::RepeatedField<global::MqGrpcProject.APIMTLSTo_a>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MqGrpcProject.APIMTLSTo_a> Oary {
      get { return oary_; }
    }

    /// <summary>Field number for the "mascnt" field.</summary>
    public const int MascntFieldNumber = 7;
    private string mascnt_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mascnt {
      get { return mascnt_; }
      set {
        mascnt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "oary2" field.</summary>
    public const int Oary2FieldNumber = 8;
    private static readonly pb::FieldCodec<global::MqGrpcProject.APIMTLSTo_a2> _repeated_oary2_codec
        = pb::FieldCodec.ForMessage(66, global::MqGrpcProject.APIMTLSTo_a2.Parser);
    private readonly pbc::RepeatedField<global::MqGrpcProject.APIMTLSTo_a2> oary2_ = new pbc::RepeatedField<global::MqGrpcProject.APIMTLSTo_a2>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MqGrpcProject.APIMTLSTo_a2> Oary2 {
      get { return oary2_; }
    }

    /// <summary>Field number for the "errmsg" field.</summary>
    public const int ErrmsgFieldNumber = 9;
    private string errmsg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Errmsg {
      get { return errmsg_; }
      set {
        errmsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as APIMTLST_Reply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(APIMTLST_Reply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Trxid != other.Trxid) return false;
      if (Typeid != other.Typeid) return false;
      if (Rtncode != other.Rtncode) return false;
      if (Rtnmesg != other.Rtnmesg) return false;
      if (Mtrlcnt != other.Mtrlcnt) return false;
      if(!oary_.Equals(other.oary_)) return false;
      if (Mascnt != other.Mascnt) return false;
      if(!oary2_.Equals(other.oary2_)) return false;
      if (Errmsg != other.Errmsg) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Trxid.Length != 0) hash ^= Trxid.GetHashCode();
      if (Typeid.Length != 0) hash ^= Typeid.GetHashCode();
      if (Rtncode.Length != 0) hash ^= Rtncode.GetHashCode();
      if (Rtnmesg.Length != 0) hash ^= Rtnmesg.GetHashCode();
      if (Mtrlcnt.Length != 0) hash ^= Mtrlcnt.GetHashCode();
      hash ^= oary_.GetHashCode();
      if (Mascnt.Length != 0) hash ^= Mascnt.GetHashCode();
      hash ^= oary2_.GetHashCode();
      if (Errmsg.Length != 0) hash ^= Errmsg.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Trxid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Trxid);
      }
      if (Typeid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Typeid);
      }
      if (Rtncode.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Rtncode);
      }
      if (Rtnmesg.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Rtnmesg);
      }
      if (Mtrlcnt.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Mtrlcnt);
      }
      oary_.WriteTo(output, _repeated_oary_codec);
      if (Mascnt.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Mascnt);
      }
      oary2_.WriteTo(output, _repeated_oary2_codec);
      if (Errmsg.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Errmsg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Trxid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Trxid);
      }
      if (Typeid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Typeid);
      }
      if (Rtncode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Rtncode);
      }
      if (Rtnmesg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Rtnmesg);
      }
      if (Mtrlcnt.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mtrlcnt);
      }
      size += oary_.CalculateSize(_repeated_oary_codec);
      if (Mascnt.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mascnt);
      }
      size += oary2_.CalculateSize(_repeated_oary2_codec);
      if (Errmsg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Errmsg);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(APIMTLST_Reply other) {
      if (other == null) {
        return;
      }
      if (other.Trxid.Length != 0) {
        Trxid = other.Trxid;
      }
      if (other.Typeid.Length != 0) {
        Typeid = other.Typeid;
      }
      if (other.Rtncode.Length != 0) {
        Rtncode = other.Rtncode;
      }
      if (other.Rtnmesg.Length != 0) {
        Rtnmesg = other.Rtnmesg;
      }
      if (other.Mtrlcnt.Length != 0) {
        Mtrlcnt = other.Mtrlcnt;
      }
      oary_.Add(other.oary_);
      if (other.Mascnt.Length != 0) {
        Mascnt = other.Mascnt;
      }
      oary2_.Add(other.oary2_);
      if (other.Errmsg.Length != 0) {
        Errmsg = other.Errmsg;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Trxid = input.ReadString();
            break;
          }
          case 18: {
            Typeid = input.ReadString();
            break;
          }
          case 26: {
            Rtncode = input.ReadString();
            break;
          }
          case 34: {
            Rtnmesg = input.ReadString();
            break;
          }
          case 42: {
            Mtrlcnt = input.ReadString();
            break;
          }
          case 50: {
            oary_.AddEntriesFrom(input, _repeated_oary_codec);
            break;
          }
          case 58: {
            Mascnt = input.ReadString();
            break;
          }
          case 66: {
            oary2_.AddEntriesFrom(input, _repeated_oary2_codec);
            break;
          }
          case 74: {
            Errmsg = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class APIMTLSTo_a : pb::IMessage<APIMTLSTo_a> {
    private static readonly pb::MessageParser<APIMTLSTo_a> _parser = new pb::MessageParser<APIMTLSTo_a>(() => new APIMTLSTo_a());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<APIMTLSTo_a> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MqGrpcProject.APIMTLSTioReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIMTLSTo_a() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIMTLSTo_a(APIMTLSTo_a other) : this() {
      mtrlproductid_ = other.mtrlproductid_;
      mtrllotid_ = other.mtrllotid_;
      seqno_ = other.seqno_;
      containerid_ = other.containerid_;
      mtrlcate_ = other.mtrlcate_;
      mtrlstat_ = other.mtrlstat_;
      mtrlqty_ = other.mtrlqty_;
      chgdate_ = other.chgdate_;
      chgtime_ = other.chgtime_;
      chguser_ = other.chguser_;
      tareqptid_ = other.tareqptid_;
      eqptid_ = other.eqptid_;
      eqptmtg_ = other.eqptmtg_;
      comment_ = other.comment_;
      mskpositionid_ = other.mskpositionid_;
      datarepdatetime_ = other.datarepdatetime_;
      oosflg_ = other.oosflg_;
      createdate_ = other.createdate_;
      expiredate_ = other.expiredate_;
      validperiod_ = other.validperiod_;
      minuseqty_ = other.minuseqty_;
      salesorder_ = other.salesorder_;
      lineid_ = other.lineid_;
      enoughflg_ = other.enoughflg_;
      lotid_ = other.lotid_;
      sheets_ = other.sheets_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIMTLSTo_a Clone() {
      return new APIMTLSTo_a(this);
    }

    /// <summary>Field number for the "mtrlproductid" field.</summary>
    public const int MtrlproductidFieldNumber = 1;
    private string mtrlproductid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mtrlproductid {
      get { return mtrlproductid_; }
      set {
        mtrlproductid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mtrllotid" field.</summary>
    public const int MtrllotidFieldNumber = 2;
    private string mtrllotid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mtrllotid {
      get { return mtrllotid_; }
      set {
        mtrllotid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "seqno" field.</summary>
    public const int SeqnoFieldNumber = 3;
    private string seqno_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Seqno {
      get { return seqno_; }
      set {
        seqno_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "containerid" field.</summary>
    public const int ContaineridFieldNumber = 4;
    private string containerid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Containerid {
      get { return containerid_; }
      set {
        containerid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mtrlcate" field.</summary>
    public const int MtrlcateFieldNumber = 5;
    private string mtrlcate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mtrlcate {
      get { return mtrlcate_; }
      set {
        mtrlcate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mtrlstat" field.</summary>
    public const int MtrlstatFieldNumber = 6;
    private string mtrlstat_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mtrlstat {
      get { return mtrlstat_; }
      set {
        mtrlstat_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mtrlqty" field.</summary>
    public const int MtrlqtyFieldNumber = 7;
    private string mtrlqty_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mtrlqty {
      get { return mtrlqty_; }
      set {
        mtrlqty_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chgdate" field.</summary>
    public const int ChgdateFieldNumber = 8;
    private string chgdate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Chgdate {
      get { return chgdate_; }
      set {
        chgdate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chgtime" field.</summary>
    public const int ChgtimeFieldNumber = 9;
    private string chgtime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Chgtime {
      get { return chgtime_; }
      set {
        chgtime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chguser" field.</summary>
    public const int ChguserFieldNumber = 10;
    private string chguser_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Chguser {
      get { return chguser_; }
      set {
        chguser_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tareqptid" field.</summary>
    public const int TareqptidFieldNumber = 11;
    private string tareqptid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Tareqptid {
      get { return tareqptid_; }
      set {
        tareqptid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "eqptid" field.</summary>
    public const int EqptidFieldNumber = 12;
    private string eqptid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Eqptid {
      get { return eqptid_; }
      set {
        eqptid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "eqptmtg" field.</summary>
    public const int EqptmtgFieldNumber = 13;
    private string eqptmtg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Eqptmtg {
      get { return eqptmtg_; }
      set {
        eqptmtg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "comment" field.</summary>
    public const int CommentFieldNumber = 14;
    private string comment_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Comment {
      get { return comment_; }
      set {
        comment_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mskpositionid" field.</summary>
    public const int MskpositionidFieldNumber = 15;
    private string mskpositionid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mskpositionid {
      get { return mskpositionid_; }
      set {
        mskpositionid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "datarepdatetime" field.</summary>
    public const int DatarepdatetimeFieldNumber = 16;
    private string datarepdatetime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Datarepdatetime {
      get { return datarepdatetime_; }
      set {
        datarepdatetime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "oosflg" field.</summary>
    public const int OosflgFieldNumber = 17;
    private string oosflg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Oosflg {
      get { return oosflg_; }
      set {
        oosflg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "createdate" field.</summary>
    public const int CreatedateFieldNumber = 18;
    private string createdate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Createdate {
      get { return createdate_; }
      set {
        createdate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "expiredate" field.</summary>
    public const int ExpiredateFieldNumber = 19;
    private string expiredate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Expiredate {
      get { return expiredate_; }
      set {
        expiredate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "validperiod" field.</summary>
    public const int ValidperiodFieldNumber = 20;
    private string validperiod_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Validperiod {
      get { return validperiod_; }
      set {
        validperiod_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "minuseqty" field.</summary>
    public const int MinuseqtyFieldNumber = 21;
    private string minuseqty_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Minuseqty {
      get { return minuseqty_; }
      set {
        minuseqty_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "salesorder" field.</summary>
    public const int SalesorderFieldNumber = 22;
    private string salesorder_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Salesorder {
      get { return salesorder_; }
      set {
        salesorder_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lineid" field.</summary>
    public const int LineidFieldNumber = 23;
    private string lineid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Lineid {
      get { return lineid_; }
      set {
        lineid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "enoughflg" field.</summary>
    public const int EnoughflgFieldNumber = 24;
    private string enoughflg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Enoughflg {
      get { return enoughflg_; }
      set {
        enoughflg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lotid" field.</summary>
    public const int LotidFieldNumber = 25;
    private string lotid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Lotid {
      get { return lotid_; }
      set {
        lotid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sheets" field.</summary>
    public const int SheetsFieldNumber = 26;
    private string sheets_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Sheets {
      get { return sheets_; }
      set {
        sheets_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as APIMTLSTo_a);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(APIMTLSTo_a other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Mtrlproductid != other.Mtrlproductid) return false;
      if (Mtrllotid != other.Mtrllotid) return false;
      if (Seqno != other.Seqno) return false;
      if (Containerid != other.Containerid) return false;
      if (Mtrlcate != other.Mtrlcate) return false;
      if (Mtrlstat != other.Mtrlstat) return false;
      if (Mtrlqty != other.Mtrlqty) return false;
      if (Chgdate != other.Chgdate) return false;
      if (Chgtime != other.Chgtime) return false;
      if (Chguser != other.Chguser) return false;
      if (Tareqptid != other.Tareqptid) return false;
      if (Eqptid != other.Eqptid) return false;
      if (Eqptmtg != other.Eqptmtg) return false;
      if (Comment != other.Comment) return false;
      if (Mskpositionid != other.Mskpositionid) return false;
      if (Datarepdatetime != other.Datarepdatetime) return false;
      if (Oosflg != other.Oosflg) return false;
      if (Createdate != other.Createdate) return false;
      if (Expiredate != other.Expiredate) return false;
      if (Validperiod != other.Validperiod) return false;
      if (Minuseqty != other.Minuseqty) return false;
      if (Salesorder != other.Salesorder) return false;
      if (Lineid != other.Lineid) return false;
      if (Enoughflg != other.Enoughflg) return false;
      if (Lotid != other.Lotid) return false;
      if (Sheets != other.Sheets) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Mtrlproductid.Length != 0) hash ^= Mtrlproductid.GetHashCode();
      if (Mtrllotid.Length != 0) hash ^= Mtrllotid.GetHashCode();
      if (Seqno.Length != 0) hash ^= Seqno.GetHashCode();
      if (Containerid.Length != 0) hash ^= Containerid.GetHashCode();
      if (Mtrlcate.Length != 0) hash ^= Mtrlcate.GetHashCode();
      if (Mtrlstat.Length != 0) hash ^= Mtrlstat.GetHashCode();
      if (Mtrlqty.Length != 0) hash ^= Mtrlqty.GetHashCode();
      if (Chgdate.Length != 0) hash ^= Chgdate.GetHashCode();
      if (Chgtime.Length != 0) hash ^= Chgtime.GetHashCode();
      if (Chguser.Length != 0) hash ^= Chguser.GetHashCode();
      if (Tareqptid.Length != 0) hash ^= Tareqptid.GetHashCode();
      if (Eqptid.Length != 0) hash ^= Eqptid.GetHashCode();
      if (Eqptmtg.Length != 0) hash ^= Eqptmtg.GetHashCode();
      if (Comment.Length != 0) hash ^= Comment.GetHashCode();
      if (Mskpositionid.Length != 0) hash ^= Mskpositionid.GetHashCode();
      if (Datarepdatetime.Length != 0) hash ^= Datarepdatetime.GetHashCode();
      if (Oosflg.Length != 0) hash ^= Oosflg.GetHashCode();
      if (Createdate.Length != 0) hash ^= Createdate.GetHashCode();
      if (Expiredate.Length != 0) hash ^= Expiredate.GetHashCode();
      if (Validperiod.Length != 0) hash ^= Validperiod.GetHashCode();
      if (Minuseqty.Length != 0) hash ^= Minuseqty.GetHashCode();
      if (Salesorder.Length != 0) hash ^= Salesorder.GetHashCode();
      if (Lineid.Length != 0) hash ^= Lineid.GetHashCode();
      if (Enoughflg.Length != 0) hash ^= Enoughflg.GetHashCode();
      if (Lotid.Length != 0) hash ^= Lotid.GetHashCode();
      if (Sheets.Length != 0) hash ^= Sheets.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Mtrlproductid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Mtrlproductid);
      }
      if (Mtrllotid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Mtrllotid);
      }
      if (Seqno.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Seqno);
      }
      if (Containerid.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Containerid);
      }
      if (Mtrlcate.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Mtrlcate);
      }
      if (Mtrlstat.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Mtrlstat);
      }
      if (Mtrlqty.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Mtrlqty);
      }
      if (Chgdate.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Chgdate);
      }
      if (Chgtime.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Chgtime);
      }
      if (Chguser.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Chguser);
      }
      if (Tareqptid.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Tareqptid);
      }
      if (Eqptid.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Eqptid);
      }
      if (Eqptmtg.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Eqptmtg);
      }
      if (Comment.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(Comment);
      }
      if (Mskpositionid.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(Mskpositionid);
      }
      if (Datarepdatetime.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(Datarepdatetime);
      }
      if (Oosflg.Length != 0) {
        output.WriteRawTag(138, 1);
        output.WriteString(Oosflg);
      }
      if (Createdate.Length != 0) {
        output.WriteRawTag(146, 1);
        output.WriteString(Createdate);
      }
      if (Expiredate.Length != 0) {
        output.WriteRawTag(154, 1);
        output.WriteString(Expiredate);
      }
      if (Validperiod.Length != 0) {
        output.WriteRawTag(162, 1);
        output.WriteString(Validperiod);
      }
      if (Minuseqty.Length != 0) {
        output.WriteRawTag(170, 1);
        output.WriteString(Minuseqty);
      }
      if (Salesorder.Length != 0) {
        output.WriteRawTag(178, 1);
        output.WriteString(Salesorder);
      }
      if (Lineid.Length != 0) {
        output.WriteRawTag(186, 1);
        output.WriteString(Lineid);
      }
      if (Enoughflg.Length != 0) {
        output.WriteRawTag(194, 1);
        output.WriteString(Enoughflg);
      }
      if (Lotid.Length != 0) {
        output.WriteRawTag(202, 1);
        output.WriteString(Lotid);
      }
      if (Sheets.Length != 0) {
        output.WriteRawTag(210, 1);
        output.WriteString(Sheets);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Mtrlproductid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mtrlproductid);
      }
      if (Mtrllotid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mtrllotid);
      }
      if (Seqno.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Seqno);
      }
      if (Containerid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Containerid);
      }
      if (Mtrlcate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mtrlcate);
      }
      if (Mtrlstat.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mtrlstat);
      }
      if (Mtrlqty.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mtrlqty);
      }
      if (Chgdate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Chgdate);
      }
      if (Chgtime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Chgtime);
      }
      if (Chguser.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Chguser);
      }
      if (Tareqptid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Tareqptid);
      }
      if (Eqptid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Eqptid);
      }
      if (Eqptmtg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Eqptmtg);
      }
      if (Comment.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Comment);
      }
      if (Mskpositionid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mskpositionid);
      }
      if (Datarepdatetime.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Datarepdatetime);
      }
      if (Oosflg.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Oosflg);
      }
      if (Createdate.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Createdate);
      }
      if (Expiredate.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Expiredate);
      }
      if (Validperiod.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Validperiod);
      }
      if (Minuseqty.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Minuseqty);
      }
      if (Salesorder.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Salesorder);
      }
      if (Lineid.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Lineid);
      }
      if (Enoughflg.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Enoughflg);
      }
      if (Lotid.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Lotid);
      }
      if (Sheets.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Sheets);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(APIMTLSTo_a other) {
      if (other == null) {
        return;
      }
      if (other.Mtrlproductid.Length != 0) {
        Mtrlproductid = other.Mtrlproductid;
      }
      if (other.Mtrllotid.Length != 0) {
        Mtrllotid = other.Mtrllotid;
      }
      if (other.Seqno.Length != 0) {
        Seqno = other.Seqno;
      }
      if (other.Containerid.Length != 0) {
        Containerid = other.Containerid;
      }
      if (other.Mtrlcate.Length != 0) {
        Mtrlcate = other.Mtrlcate;
      }
      if (other.Mtrlstat.Length != 0) {
        Mtrlstat = other.Mtrlstat;
      }
      if (other.Mtrlqty.Length != 0) {
        Mtrlqty = other.Mtrlqty;
      }
      if (other.Chgdate.Length != 0) {
        Chgdate = other.Chgdate;
      }
      if (other.Chgtime.Length != 0) {
        Chgtime = other.Chgtime;
      }
      if (other.Chguser.Length != 0) {
        Chguser = other.Chguser;
      }
      if (other.Tareqptid.Length != 0) {
        Tareqptid = other.Tareqptid;
      }
      if (other.Eqptid.Length != 0) {
        Eqptid = other.Eqptid;
      }
      if (other.Eqptmtg.Length != 0) {
        Eqptmtg = other.Eqptmtg;
      }
      if (other.Comment.Length != 0) {
        Comment = other.Comment;
      }
      if (other.Mskpositionid.Length != 0) {
        Mskpositionid = other.Mskpositionid;
      }
      if (other.Datarepdatetime.Length != 0) {
        Datarepdatetime = other.Datarepdatetime;
      }
      if (other.Oosflg.Length != 0) {
        Oosflg = other.Oosflg;
      }
      if (other.Createdate.Length != 0) {
        Createdate = other.Createdate;
      }
      if (other.Expiredate.Length != 0) {
        Expiredate = other.Expiredate;
      }
      if (other.Validperiod.Length != 0) {
        Validperiod = other.Validperiod;
      }
      if (other.Minuseqty.Length != 0) {
        Minuseqty = other.Minuseqty;
      }
      if (other.Salesorder.Length != 0) {
        Salesorder = other.Salesorder;
      }
      if (other.Lineid.Length != 0) {
        Lineid = other.Lineid;
      }
      if (other.Enoughflg.Length != 0) {
        Enoughflg = other.Enoughflg;
      }
      if (other.Lotid.Length != 0) {
        Lotid = other.Lotid;
      }
      if (other.Sheets.Length != 0) {
        Sheets = other.Sheets;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Mtrlproductid = input.ReadString();
            break;
          }
          case 18: {
            Mtrllotid = input.ReadString();
            break;
          }
          case 26: {
            Seqno = input.ReadString();
            break;
          }
          case 34: {
            Containerid = input.ReadString();
            break;
          }
          case 42: {
            Mtrlcate = input.ReadString();
            break;
          }
          case 50: {
            Mtrlstat = input.ReadString();
            break;
          }
          case 58: {
            Mtrlqty = input.ReadString();
            break;
          }
          case 66: {
            Chgdate = input.ReadString();
            break;
          }
          case 74: {
            Chgtime = input.ReadString();
            break;
          }
          case 82: {
            Chguser = input.ReadString();
            break;
          }
          case 90: {
            Tareqptid = input.ReadString();
            break;
          }
          case 98: {
            Eqptid = input.ReadString();
            break;
          }
          case 106: {
            Eqptmtg = input.ReadString();
            break;
          }
          case 114: {
            Comment = input.ReadString();
            break;
          }
          case 122: {
            Mskpositionid = input.ReadString();
            break;
          }
          case 130: {
            Datarepdatetime = input.ReadString();
            break;
          }
          case 138: {
            Oosflg = input.ReadString();
            break;
          }
          case 146: {
            Createdate = input.ReadString();
            break;
          }
          case 154: {
            Expiredate = input.ReadString();
            break;
          }
          case 162: {
            Validperiod = input.ReadString();
            break;
          }
          case 170: {
            Minuseqty = input.ReadString();
            break;
          }
          case 178: {
            Salesorder = input.ReadString();
            break;
          }
          case 186: {
            Lineid = input.ReadString();
            break;
          }
          case 194: {
            Enoughflg = input.ReadString();
            break;
          }
          case 202: {
            Lotid = input.ReadString();
            break;
          }
          case 210: {
            Sheets = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class APIMTLSTo_a2 : pb::IMessage<APIMTLSTo_a2> {
    private static readonly pb::MessageParser<APIMTLSTo_a2> _parser = new pb::MessageParser<APIMTLSTo_a2>(() => new APIMTLSTo_a2());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<APIMTLSTo_a2> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MqGrpcProject.APIMTLSTioReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIMTLSTo_a2() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIMTLSTo_a2(APIMTLSTo_a2 other) : this() {
      mtrlprodid_ = other.mtrlprodid_;
      submtrlprodid_ = other.submtrlprodid_;
      proportion_ = other.proportion_;
      userid_ = other.userid_;
      chgdate_ = other.chgdate_;
      chgtime_ = other.chgtime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIMTLSTo_a2 Clone() {
      return new APIMTLSTo_a2(this);
    }

    /// <summary>Field number for the "mtrlprodid" field.</summary>
    public const int MtrlprodidFieldNumber = 1;
    private string mtrlprodid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mtrlprodid {
      get { return mtrlprodid_; }
      set {
        mtrlprodid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "submtrlprodid" field.</summary>
    public const int SubmtrlprodidFieldNumber = 2;
    private string submtrlprodid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Submtrlprodid {
      get { return submtrlprodid_; }
      set {
        submtrlprodid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "proportion" field.</summary>
    public const int ProportionFieldNumber = 3;
    private string proportion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Proportion {
      get { return proportion_; }
      set {
        proportion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "userid" field.</summary>
    public const int UseridFieldNumber = 4;
    private string userid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Userid {
      get { return userid_; }
      set {
        userid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chgdate" field.</summary>
    public const int ChgdateFieldNumber = 5;
    private string chgdate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Chgdate {
      get { return chgdate_; }
      set {
        chgdate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chgtime" field.</summary>
    public const int ChgtimeFieldNumber = 6;
    private string chgtime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Chgtime {
      get { return chgtime_; }
      set {
        chgtime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as APIMTLSTo_a2);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(APIMTLSTo_a2 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Mtrlprodid != other.Mtrlprodid) return false;
      if (Submtrlprodid != other.Submtrlprodid) return false;
      if (Proportion != other.Proportion) return false;
      if (Userid != other.Userid) return false;
      if (Chgdate != other.Chgdate) return false;
      if (Chgtime != other.Chgtime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Mtrlprodid.Length != 0) hash ^= Mtrlprodid.GetHashCode();
      if (Submtrlprodid.Length != 0) hash ^= Submtrlprodid.GetHashCode();
      if (Proportion.Length != 0) hash ^= Proportion.GetHashCode();
      if (Userid.Length != 0) hash ^= Userid.GetHashCode();
      if (Chgdate.Length != 0) hash ^= Chgdate.GetHashCode();
      if (Chgtime.Length != 0) hash ^= Chgtime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Mtrlprodid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Mtrlprodid);
      }
      if (Submtrlprodid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Submtrlprodid);
      }
      if (Proportion.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Proportion);
      }
      if (Userid.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Userid);
      }
      if (Chgdate.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Chgdate);
      }
      if (Chgtime.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Chgtime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Mtrlprodid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mtrlprodid);
      }
      if (Submtrlprodid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Submtrlprodid);
      }
      if (Proportion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Proportion);
      }
      if (Userid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Userid);
      }
      if (Chgdate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Chgdate);
      }
      if (Chgtime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Chgtime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(APIMTLSTo_a2 other) {
      if (other == null) {
        return;
      }
      if (other.Mtrlprodid.Length != 0) {
        Mtrlprodid = other.Mtrlprodid;
      }
      if (other.Submtrlprodid.Length != 0) {
        Submtrlprodid = other.Submtrlprodid;
      }
      if (other.Proportion.Length != 0) {
        Proportion = other.Proportion;
      }
      if (other.Userid.Length != 0) {
        Userid = other.Userid;
      }
      if (other.Chgdate.Length != 0) {
        Chgdate = other.Chgdate;
      }
      if (other.Chgtime.Length != 0) {
        Chgtime = other.Chgtime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Mtrlprodid = input.ReadString();
            break;
          }
          case 18: {
            Submtrlprodid = input.ReadString();
            break;
          }
          case 26: {
            Proportion = input.ReadString();
            break;
          }
          case 34: {
            Userid = input.ReadString();
            break;
          }
          case 42: {
            Chgdate = input.ReadString();
            break;
          }
          case 50: {
            Chgtime = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
