// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: APLPRDBMio.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MqGrpcProject {

  /// <summary>Holder for reflection information generated from APLPRDBMio.proto</summary>
  public static partial class APLPRDBMioReflection {

    #region Descriptor
    /// <summary>File descriptor for APLPRDBMio.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static APLPRDBMioReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBBUExQUkRCTWlvLnByb3RvEg1NcUdycGNQcm9qZWN0Iv8BChBBUExQUkRC",
            "TV9SZXF1ZXN0EhEKCXByb2R1Y3RpZBgBIAEoCRIOCgZlY2NvZGUYAiABKAkS",
            "EQoJcm91dGVjYXRlGAMgASgJEg8KB3JvdXRlaWQYBCABKAkSEAoIcm91dGV2",
            "ZXIYBSABKAkSDQoFb3BlaWQYBiABKAkSDgoGb3BldmVyGAcgASgJEhIKCnJl",
            "c3ZlcXB0aWQYCCABKAkSDQoFbG90aWQYCSABKAkSDwoHbnhvcGVubxgKIAEo",
            "CRIWCg51c2VyZWN5Y2xlZmxhZxgLIAEoCRIVCg1tb3Zlb3V0bGVuZ2h0GAwg",
            "ASgJEhAKCHNlcnZlcmlwGA0gASgJIp8CCg5BUExQUkRCTV9SZXBseRINCgV0",
            "cnhpZBgBIAEoCRIOCgZ0eXBlaWQYAiABKAkSDwoHcnRuY29kZRgDIAEoCRIP",
            "CgdydG5tZXNnGAQgASgJEhEKCXByb2R1Y3RpZBgFIAEoCRIOCgZlY2NvZGUY",
            "BiABKAkSDwoHcm91dGVpZBgHIAEoCRIQCghyb3V0ZXZlchgIIAEoCRIOCgZi",
            "b21jbnQYCSABKAkSKgoFb2FyeTEYCiADKAsyGy5NcUdycGNQcm9qZWN0LkFQ",
            "TFBSREJNb19hMRIPCgdzcGVjY250GAsgASgJEikKBW9hcnkzGAwgAygLMhou",
            "TXFHcnBjUHJvamVjdC5BUExQUkRCTW9fYRIOCgZlcnJtc2cYDSABKAki0wEK",
            "DEFQTFBSREJNb19hMRINCgVvcGVpZBgBIAEoCRIOCgZvcGV2ZXIYAiABKAkS",
            "DQoFYm9taWQYAyABKAkSDgoGYm9tZHNjGAQgASgJEg8KB3N0YWdlaWQYBSAB",
            "KAkSEQoJYWRkdGluZm8xGAYgASgJEhEKCWFkZHRpbmZvMhgHIAEoCRIRCglh",
            "ZGR0aW5mbzMYCCABKAkSDwoHbXRybGNudBgJIAEoCRIqCgVvYXJ5MhgKIAMo",
            "CzIbLk1xR3JwY1Byb2plY3QuQVBMUFJEQk1vX2EyIucBCgxBUExQUkRCTW9f",
            "YTISFQoNbXRybHByb2R1Y3RpZBgBIAEoCRIWCg5tdHJscHJvZHVjdGRzYxgC",
            "IAEoCRIQCghtdHJsY2F0ZRgDIAEoCRIPCgdwbGFucXR5GAQgASgJEhAKCG10",
            "cmx1bml0GAUgASgJEhYKDnNwY2Z5bXRybGxvdGlkGAYgASgJEg0KBWV4dF8x",
            "GAcgASgJEg0KBWV4dF8yGAggASgJEg0KBWV4dF8zGAkgASgJEg0KBWV4dF80",
            "GAogASgJEg0KBWV4dF81GAsgASgJEhAKCHBhcmVudGlkGAwgASgJIiwKC0FQ",
            "TFBSREJNb19hEg0KBXNuYW1lGAEgASgJEg4KBnN2YWx1ZRgCIAEoCUIzChVp",
            "by5ncnBjLk1xR3JwY1Byb2plY3RCEk1xR3JwY1Byb2plY3RQcm90b1ABogID",
            "SExXYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MqGrpcProject.APLPRDBM_Request), global::MqGrpcProject.APLPRDBM_Request.Parser, new[]{ "Productid", "Eccode", "Routecate", "Routeid", "Routever", "Opeid", "Opever", "Resveqptid", "Lotid", "Nxopeno", "Userecycleflag", "Moveoutlenght", "Serverip" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MqGrpcProject.APLPRDBM_Reply), global::MqGrpcProject.APLPRDBM_Reply.Parser, new[]{ "Trxid", "Typeid", "Rtncode", "Rtnmesg", "Productid", "Eccode", "Routeid", "Routever", "Bomcnt", "Oary1", "Speccnt", "Oary3", "Errmsg" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MqGrpcProject.APLPRDBMo_a1), global::MqGrpcProject.APLPRDBMo_a1.Parser, new[]{ "Opeid", "Opever", "Bomid", "Bomdsc", "Stageid", "Addtinfo1", "Addtinfo2", "Addtinfo3", "Mtrlcnt", "Oary2" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MqGrpcProject.APLPRDBMo_a2), global::MqGrpcProject.APLPRDBMo_a2.Parser, new[]{ "Mtrlproductid", "Mtrlproductdsc", "Mtrlcate", "Planqty", "Mtrlunit", "Spcfymtrllotid", "Ext1", "Ext2", "Ext3", "Ext4", "Ext5", "Parentid" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MqGrpcProject.APLPRDBMo_a), global::MqGrpcProject.APLPRDBMo_a.Parser, new[]{ "Sname", "Svalue" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class APLPRDBM_Request : pb::IMessage<APLPRDBM_Request> {
    private static readonly pb::MessageParser<APLPRDBM_Request> _parser = new pb::MessageParser<APLPRDBM_Request>(() => new APLPRDBM_Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<APLPRDBM_Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MqGrpcProject.APLPRDBMioReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APLPRDBM_Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APLPRDBM_Request(APLPRDBM_Request other) : this() {
      productid_ = other.productid_;
      eccode_ = other.eccode_;
      routecate_ = other.routecate_;
      routeid_ = other.routeid_;
      routever_ = other.routever_;
      opeid_ = other.opeid_;
      opever_ = other.opever_;
      resveqptid_ = other.resveqptid_;
      lotid_ = other.lotid_;
      nxopeno_ = other.nxopeno_;
      userecycleflag_ = other.userecycleflag_;
      moveoutlenght_ = other.moveoutlenght_;
      serverip_ = other.serverip_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APLPRDBM_Request Clone() {
      return new APLPRDBM_Request(this);
    }

    /// <summary>Field number for the "productid" field.</summary>
    public const int ProductidFieldNumber = 1;
    private string productid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Productid {
      get { return productid_; }
      set {
        productid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "eccode" field.</summary>
    public const int EccodeFieldNumber = 2;
    private string eccode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Eccode {
      get { return eccode_; }
      set {
        eccode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "routecate" field.</summary>
    public const int RoutecateFieldNumber = 3;
    private string routecate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Routecate {
      get { return routecate_; }
      set {
        routecate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "routeid" field.</summary>
    public const int RouteidFieldNumber = 4;
    private string routeid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Routeid {
      get { return routeid_; }
      set {
        routeid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "routever" field.</summary>
    public const int RouteverFieldNumber = 5;
    private string routever_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Routever {
      get { return routever_; }
      set {
        routever_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "opeid" field.</summary>
    public const int OpeidFieldNumber = 6;
    private string opeid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Opeid {
      get { return opeid_; }
      set {
        opeid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "opever" field.</summary>
    public const int OpeverFieldNumber = 7;
    private string opever_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Opever {
      get { return opever_; }
      set {
        opever_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "resveqptid" field.</summary>
    public const int ResveqptidFieldNumber = 8;
    private string resveqptid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Resveqptid {
      get { return resveqptid_; }
      set {
        resveqptid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lotid" field.</summary>
    public const int LotidFieldNumber = 9;
    private string lotid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Lotid {
      get { return lotid_; }
      set {
        lotid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nxopeno" field.</summary>
    public const int NxopenoFieldNumber = 10;
    private string nxopeno_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Nxopeno {
      get { return nxopeno_; }
      set {
        nxopeno_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "userecycleflag" field.</summary>
    public const int UserecycleflagFieldNumber = 11;
    private string userecycleflag_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Userecycleflag {
      get { return userecycleflag_; }
      set {
        userecycleflag_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "moveoutlenght" field.</summary>
    public const int MoveoutlenghtFieldNumber = 12;
    private string moveoutlenght_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Moveoutlenght {
      get { return moveoutlenght_; }
      set {
        moveoutlenght_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "serverip" field.</summary>
    public const int ServeripFieldNumber = 13;
    private string serverip_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Serverip {
      get { return serverip_; }
      set {
        serverip_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as APLPRDBM_Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(APLPRDBM_Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Productid != other.Productid) return false;
      if (Eccode != other.Eccode) return false;
      if (Routecate != other.Routecate) return false;
      if (Routeid != other.Routeid) return false;
      if (Routever != other.Routever) return false;
      if (Opeid != other.Opeid) return false;
      if (Opever != other.Opever) return false;
      if (Resveqptid != other.Resveqptid) return false;
      if (Lotid != other.Lotid) return false;
      if (Nxopeno != other.Nxopeno) return false;
      if (Userecycleflag != other.Userecycleflag) return false;
      if (Moveoutlenght != other.Moveoutlenght) return false;
      if (Serverip != other.Serverip) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Productid.Length != 0) hash ^= Productid.GetHashCode();
      if (Eccode.Length != 0) hash ^= Eccode.GetHashCode();
      if (Routecate.Length != 0) hash ^= Routecate.GetHashCode();
      if (Routeid.Length != 0) hash ^= Routeid.GetHashCode();
      if (Routever.Length != 0) hash ^= Routever.GetHashCode();
      if (Opeid.Length != 0) hash ^= Opeid.GetHashCode();
      if (Opever.Length != 0) hash ^= Opever.GetHashCode();
      if (Resveqptid.Length != 0) hash ^= Resveqptid.GetHashCode();
      if (Lotid.Length != 0) hash ^= Lotid.GetHashCode();
      if (Nxopeno.Length != 0) hash ^= Nxopeno.GetHashCode();
      if (Userecycleflag.Length != 0) hash ^= Userecycleflag.GetHashCode();
      if (Moveoutlenght.Length != 0) hash ^= Moveoutlenght.GetHashCode();
      if (Serverip.Length != 0) hash ^= Serverip.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Productid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Productid);
      }
      if (Eccode.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Eccode);
      }
      if (Routecate.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Routecate);
      }
      if (Routeid.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Routeid);
      }
      if (Routever.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Routever);
      }
      if (Opeid.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Opeid);
      }
      if (Opever.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Opever);
      }
      if (Resveqptid.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Resveqptid);
      }
      if (Lotid.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Lotid);
      }
      if (Nxopeno.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Nxopeno);
      }
      if (Userecycleflag.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Userecycleflag);
      }
      if (Moveoutlenght.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Moveoutlenght);
      }
      if (Serverip.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Serverip);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Productid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Productid);
      }
      if (Eccode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Eccode);
      }
      if (Routecate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Routecate);
      }
      if (Routeid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Routeid);
      }
      if (Routever.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Routever);
      }
      if (Opeid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Opeid);
      }
      if (Opever.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Opever);
      }
      if (Resveqptid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Resveqptid);
      }
      if (Lotid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Lotid);
      }
      if (Nxopeno.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nxopeno);
      }
      if (Userecycleflag.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Userecycleflag);
      }
      if (Moveoutlenght.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Moveoutlenght);
      }
      if (Serverip.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Serverip);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(APLPRDBM_Request other) {
      if (other == null) {
        return;
      }
      if (other.Productid.Length != 0) {
        Productid = other.Productid;
      }
      if (other.Eccode.Length != 0) {
        Eccode = other.Eccode;
      }
      if (other.Routecate.Length != 0) {
        Routecate = other.Routecate;
      }
      if (other.Routeid.Length != 0) {
        Routeid = other.Routeid;
      }
      if (other.Routever.Length != 0) {
        Routever = other.Routever;
      }
      if (other.Opeid.Length != 0) {
        Opeid = other.Opeid;
      }
      if (other.Opever.Length != 0) {
        Opever = other.Opever;
      }
      if (other.Resveqptid.Length != 0) {
        Resveqptid = other.Resveqptid;
      }
      if (other.Lotid.Length != 0) {
        Lotid = other.Lotid;
      }
      if (other.Nxopeno.Length != 0) {
        Nxopeno = other.Nxopeno;
      }
      if (other.Userecycleflag.Length != 0) {
        Userecycleflag = other.Userecycleflag;
      }
      if (other.Moveoutlenght.Length != 0) {
        Moveoutlenght = other.Moveoutlenght;
      }
      if (other.Serverip.Length != 0) {
        Serverip = other.Serverip;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Productid = input.ReadString();
            break;
          }
          case 18: {
            Eccode = input.ReadString();
            break;
          }
          case 26: {
            Routecate = input.ReadString();
            break;
          }
          case 34: {
            Routeid = input.ReadString();
            break;
          }
          case 42: {
            Routever = input.ReadString();
            break;
          }
          case 50: {
            Opeid = input.ReadString();
            break;
          }
          case 58: {
            Opever = input.ReadString();
            break;
          }
          case 66: {
            Resveqptid = input.ReadString();
            break;
          }
          case 74: {
            Lotid = input.ReadString();
            break;
          }
          case 82: {
            Nxopeno = input.ReadString();
            break;
          }
          case 90: {
            Userecycleflag = input.ReadString();
            break;
          }
          case 98: {
            Moveoutlenght = input.ReadString();
            break;
          }
          case 106: {
            Serverip = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class APLPRDBM_Reply : pb::IMessage<APLPRDBM_Reply> {
    private static readonly pb::MessageParser<APLPRDBM_Reply> _parser = new pb::MessageParser<APLPRDBM_Reply>(() => new APLPRDBM_Reply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<APLPRDBM_Reply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MqGrpcProject.APLPRDBMioReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APLPRDBM_Reply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APLPRDBM_Reply(APLPRDBM_Reply other) : this() {
      trxid_ = other.trxid_;
      typeid_ = other.typeid_;
      rtncode_ = other.rtncode_;
      rtnmesg_ = other.rtnmesg_;
      productid_ = other.productid_;
      eccode_ = other.eccode_;
      routeid_ = other.routeid_;
      routever_ = other.routever_;
      bomcnt_ = other.bomcnt_;
      oary1_ = other.oary1_.Clone();
      speccnt_ = other.speccnt_;
      oary3_ = other.oary3_.Clone();
      errmsg_ = other.errmsg_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APLPRDBM_Reply Clone() {
      return new APLPRDBM_Reply(this);
    }

    /// <summary>Field number for the "trxid" field.</summary>
    public const int TrxidFieldNumber = 1;
    private string trxid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Trxid {
      get { return trxid_; }
      set {
        trxid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "typeid" field.</summary>
    public const int TypeidFieldNumber = 2;
    private string typeid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Typeid {
      get { return typeid_; }
      set {
        typeid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "rtncode" field.</summary>
    public const int RtncodeFieldNumber = 3;
    private string rtncode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Rtncode {
      get { return rtncode_; }
      set {
        rtncode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "rtnmesg" field.</summary>
    public const int RtnmesgFieldNumber = 4;
    private string rtnmesg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Rtnmesg {
      get { return rtnmesg_; }
      set {
        rtnmesg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "productid" field.</summary>
    public const int ProductidFieldNumber = 5;
    private string productid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Productid {
      get { return productid_; }
      set {
        productid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "eccode" field.</summary>
    public const int EccodeFieldNumber = 6;
    private string eccode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Eccode {
      get { return eccode_; }
      set {
        eccode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "routeid" field.</summary>
    public const int RouteidFieldNumber = 7;
    private string routeid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Routeid {
      get { return routeid_; }
      set {
        routeid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "routever" field.</summary>
    public const int RouteverFieldNumber = 8;
    private string routever_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Routever {
      get { return routever_; }
      set {
        routever_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bomcnt" field.</summary>
    public const int BomcntFieldNumber = 9;
    private string bomcnt_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Bomcnt {
      get { return bomcnt_; }
      set {
        bomcnt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "oary1" field.</summary>
    public const int Oary1FieldNumber = 10;
    private static readonly pb::FieldCodec<global::MqGrpcProject.APLPRDBMo_a1> _repeated_oary1_codec
        = pb::FieldCodec.ForMessage(82, global::MqGrpcProject.APLPRDBMo_a1.Parser);
    private readonly pbc::RepeatedField<global::MqGrpcProject.APLPRDBMo_a1> oary1_ = new pbc::RepeatedField<global::MqGrpcProject.APLPRDBMo_a1>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MqGrpcProject.APLPRDBMo_a1> Oary1 {
      get { return oary1_; }
    }

    /// <summary>Field number for the "speccnt" field.</summary>
    public const int SpeccntFieldNumber = 11;
    private string speccnt_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Speccnt {
      get { return speccnt_; }
      set {
        speccnt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "oary3" field.</summary>
    public const int Oary3FieldNumber = 12;
    private static readonly pb::FieldCodec<global::MqGrpcProject.APLPRDBMo_a> _repeated_oary3_codec
        = pb::FieldCodec.ForMessage(98, global::MqGrpcProject.APLPRDBMo_a.Parser);
    private readonly pbc::RepeatedField<global::MqGrpcProject.APLPRDBMo_a> oary3_ = new pbc::RepeatedField<global::MqGrpcProject.APLPRDBMo_a>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MqGrpcProject.APLPRDBMo_a> Oary3 {
      get { return oary3_; }
    }

    /// <summary>Field number for the "errmsg" field.</summary>
    public const int ErrmsgFieldNumber = 13;
    private string errmsg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Errmsg {
      get { return errmsg_; }
      set {
        errmsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as APLPRDBM_Reply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(APLPRDBM_Reply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Trxid != other.Trxid) return false;
      if (Typeid != other.Typeid) return false;
      if (Rtncode != other.Rtncode) return false;
      if (Rtnmesg != other.Rtnmesg) return false;
      if (Productid != other.Productid) return false;
      if (Eccode != other.Eccode) return false;
      if (Routeid != other.Routeid) return false;
      if (Routever != other.Routever) return false;
      if (Bomcnt != other.Bomcnt) return false;
      if(!oary1_.Equals(other.oary1_)) return false;
      if (Speccnt != other.Speccnt) return false;
      if(!oary3_.Equals(other.oary3_)) return false;
      if (Errmsg != other.Errmsg) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Trxid.Length != 0) hash ^= Trxid.GetHashCode();
      if (Typeid.Length != 0) hash ^= Typeid.GetHashCode();
      if (Rtncode.Length != 0) hash ^= Rtncode.GetHashCode();
      if (Rtnmesg.Length != 0) hash ^= Rtnmesg.GetHashCode();
      if (Productid.Length != 0) hash ^= Productid.GetHashCode();
      if (Eccode.Length != 0) hash ^= Eccode.GetHashCode();
      if (Routeid.Length != 0) hash ^= Routeid.GetHashCode();
      if (Routever.Length != 0) hash ^= Routever.GetHashCode();
      if (Bomcnt.Length != 0) hash ^= Bomcnt.GetHashCode();
      hash ^= oary1_.GetHashCode();
      if (Speccnt.Length != 0) hash ^= Speccnt.GetHashCode();
      hash ^= oary3_.GetHashCode();
      if (Errmsg.Length != 0) hash ^= Errmsg.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Trxid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Trxid);
      }
      if (Typeid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Typeid);
      }
      if (Rtncode.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Rtncode);
      }
      if (Rtnmesg.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Rtnmesg);
      }
      if (Productid.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Productid);
      }
      if (Eccode.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Eccode);
      }
      if (Routeid.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Routeid);
      }
      if (Routever.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Routever);
      }
      if (Bomcnt.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Bomcnt);
      }
      oary1_.WriteTo(output, _repeated_oary1_codec);
      if (Speccnt.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Speccnt);
      }
      oary3_.WriteTo(output, _repeated_oary3_codec);
      if (Errmsg.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Errmsg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Trxid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Trxid);
      }
      if (Typeid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Typeid);
      }
      if (Rtncode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Rtncode);
      }
      if (Rtnmesg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Rtnmesg);
      }
      if (Productid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Productid);
      }
      if (Eccode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Eccode);
      }
      if (Routeid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Routeid);
      }
      if (Routever.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Routever);
      }
      if (Bomcnt.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Bomcnt);
      }
      size += oary1_.CalculateSize(_repeated_oary1_codec);
      if (Speccnt.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Speccnt);
      }
      size += oary3_.CalculateSize(_repeated_oary3_codec);
      if (Errmsg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Errmsg);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(APLPRDBM_Reply other) {
      if (other == null) {
        return;
      }
      if (other.Trxid.Length != 0) {
        Trxid = other.Trxid;
      }
      if (other.Typeid.Length != 0) {
        Typeid = other.Typeid;
      }
      if (other.Rtncode.Length != 0) {
        Rtncode = other.Rtncode;
      }
      if (other.Rtnmesg.Length != 0) {
        Rtnmesg = other.Rtnmesg;
      }
      if (other.Productid.Length != 0) {
        Productid = other.Productid;
      }
      if (other.Eccode.Length != 0) {
        Eccode = other.Eccode;
      }
      if (other.Routeid.Length != 0) {
        Routeid = other.Routeid;
      }
      if (other.Routever.Length != 0) {
        Routever = other.Routever;
      }
      if (other.Bomcnt.Length != 0) {
        Bomcnt = other.Bomcnt;
      }
      oary1_.Add(other.oary1_);
      if (other.Speccnt.Length != 0) {
        Speccnt = other.Speccnt;
      }
      oary3_.Add(other.oary3_);
      if (other.Errmsg.Length != 0) {
        Errmsg = other.Errmsg;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Trxid = input.ReadString();
            break;
          }
          case 18: {
            Typeid = input.ReadString();
            break;
          }
          case 26: {
            Rtncode = input.ReadString();
            break;
          }
          case 34: {
            Rtnmesg = input.ReadString();
            break;
          }
          case 42: {
            Productid = input.ReadString();
            break;
          }
          case 50: {
            Eccode = input.ReadString();
            break;
          }
          case 58: {
            Routeid = input.ReadString();
            break;
          }
          case 66: {
            Routever = input.ReadString();
            break;
          }
          case 74: {
            Bomcnt = input.ReadString();
            break;
          }
          case 82: {
            oary1_.AddEntriesFrom(input, _repeated_oary1_codec);
            break;
          }
          case 90: {
            Speccnt = input.ReadString();
            break;
          }
          case 98: {
            oary3_.AddEntriesFrom(input, _repeated_oary3_codec);
            break;
          }
          case 106: {
            Errmsg = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class APLPRDBMo_a1 : pb::IMessage<APLPRDBMo_a1> {
    private static readonly pb::MessageParser<APLPRDBMo_a1> _parser = new pb::MessageParser<APLPRDBMo_a1>(() => new APLPRDBMo_a1());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<APLPRDBMo_a1> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MqGrpcProject.APLPRDBMioReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APLPRDBMo_a1() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APLPRDBMo_a1(APLPRDBMo_a1 other) : this() {
      opeid_ = other.opeid_;
      opever_ = other.opever_;
      bomid_ = other.bomid_;
      bomdsc_ = other.bomdsc_;
      stageid_ = other.stageid_;
      addtinfo1_ = other.addtinfo1_;
      addtinfo2_ = other.addtinfo2_;
      addtinfo3_ = other.addtinfo3_;
      mtrlcnt_ = other.mtrlcnt_;
      oary2_ = other.oary2_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APLPRDBMo_a1 Clone() {
      return new APLPRDBMo_a1(this);
    }

    /// <summary>Field number for the "opeid" field.</summary>
    public const int OpeidFieldNumber = 1;
    private string opeid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Opeid {
      get { return opeid_; }
      set {
        opeid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "opever" field.</summary>
    public const int OpeverFieldNumber = 2;
    private string opever_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Opever {
      get { return opever_; }
      set {
        opever_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bomid" field.</summary>
    public const int BomidFieldNumber = 3;
    private string bomid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Bomid {
      get { return bomid_; }
      set {
        bomid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bomdsc" field.</summary>
    public const int BomdscFieldNumber = 4;
    private string bomdsc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Bomdsc {
      get { return bomdsc_; }
      set {
        bomdsc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "stageid" field.</summary>
    public const int StageidFieldNumber = 5;
    private string stageid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Stageid {
      get { return stageid_; }
      set {
        stageid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "addtinfo1" field.</summary>
    public const int Addtinfo1FieldNumber = 6;
    private string addtinfo1_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Addtinfo1 {
      get { return addtinfo1_; }
      set {
        addtinfo1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "addtinfo2" field.</summary>
    public const int Addtinfo2FieldNumber = 7;
    private string addtinfo2_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Addtinfo2 {
      get { return addtinfo2_; }
      set {
        addtinfo2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "addtinfo3" field.</summary>
    public const int Addtinfo3FieldNumber = 8;
    private string addtinfo3_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Addtinfo3 {
      get { return addtinfo3_; }
      set {
        addtinfo3_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mtrlcnt" field.</summary>
    public const int MtrlcntFieldNumber = 9;
    private string mtrlcnt_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mtrlcnt {
      get { return mtrlcnt_; }
      set {
        mtrlcnt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "oary2" field.</summary>
    public const int Oary2FieldNumber = 10;
    private static readonly pb::FieldCodec<global::MqGrpcProject.APLPRDBMo_a2> _repeated_oary2_codec
        = pb::FieldCodec.ForMessage(82, global::MqGrpcProject.APLPRDBMo_a2.Parser);
    private readonly pbc::RepeatedField<global::MqGrpcProject.APLPRDBMo_a2> oary2_ = new pbc::RepeatedField<global::MqGrpcProject.APLPRDBMo_a2>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MqGrpcProject.APLPRDBMo_a2> Oary2 {
      get { return oary2_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as APLPRDBMo_a1);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(APLPRDBMo_a1 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Opeid != other.Opeid) return false;
      if (Opever != other.Opever) return false;
      if (Bomid != other.Bomid) return false;
      if (Bomdsc != other.Bomdsc) return false;
      if (Stageid != other.Stageid) return false;
      if (Addtinfo1 != other.Addtinfo1) return false;
      if (Addtinfo2 != other.Addtinfo2) return false;
      if (Addtinfo3 != other.Addtinfo3) return false;
      if (Mtrlcnt != other.Mtrlcnt) return false;
      if(!oary2_.Equals(other.oary2_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Opeid.Length != 0) hash ^= Opeid.GetHashCode();
      if (Opever.Length != 0) hash ^= Opever.GetHashCode();
      if (Bomid.Length != 0) hash ^= Bomid.GetHashCode();
      if (Bomdsc.Length != 0) hash ^= Bomdsc.GetHashCode();
      if (Stageid.Length != 0) hash ^= Stageid.GetHashCode();
      if (Addtinfo1.Length != 0) hash ^= Addtinfo1.GetHashCode();
      if (Addtinfo2.Length != 0) hash ^= Addtinfo2.GetHashCode();
      if (Addtinfo3.Length != 0) hash ^= Addtinfo3.GetHashCode();
      if (Mtrlcnt.Length != 0) hash ^= Mtrlcnt.GetHashCode();
      hash ^= oary2_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Opeid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Opeid);
      }
      if (Opever.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Opever);
      }
      if (Bomid.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Bomid);
      }
      if (Bomdsc.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Bomdsc);
      }
      if (Stageid.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Stageid);
      }
      if (Addtinfo1.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Addtinfo1);
      }
      if (Addtinfo2.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Addtinfo2);
      }
      if (Addtinfo3.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Addtinfo3);
      }
      if (Mtrlcnt.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Mtrlcnt);
      }
      oary2_.WriteTo(output, _repeated_oary2_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Opeid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Opeid);
      }
      if (Opever.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Opever);
      }
      if (Bomid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Bomid);
      }
      if (Bomdsc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Bomdsc);
      }
      if (Stageid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Stageid);
      }
      if (Addtinfo1.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Addtinfo1);
      }
      if (Addtinfo2.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Addtinfo2);
      }
      if (Addtinfo3.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Addtinfo3);
      }
      if (Mtrlcnt.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mtrlcnt);
      }
      size += oary2_.CalculateSize(_repeated_oary2_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(APLPRDBMo_a1 other) {
      if (other == null) {
        return;
      }
      if (other.Opeid.Length != 0) {
        Opeid = other.Opeid;
      }
      if (other.Opever.Length != 0) {
        Opever = other.Opever;
      }
      if (other.Bomid.Length != 0) {
        Bomid = other.Bomid;
      }
      if (other.Bomdsc.Length != 0) {
        Bomdsc = other.Bomdsc;
      }
      if (other.Stageid.Length != 0) {
        Stageid = other.Stageid;
      }
      if (other.Addtinfo1.Length != 0) {
        Addtinfo1 = other.Addtinfo1;
      }
      if (other.Addtinfo2.Length != 0) {
        Addtinfo2 = other.Addtinfo2;
      }
      if (other.Addtinfo3.Length != 0) {
        Addtinfo3 = other.Addtinfo3;
      }
      if (other.Mtrlcnt.Length != 0) {
        Mtrlcnt = other.Mtrlcnt;
      }
      oary2_.Add(other.oary2_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Opeid = input.ReadString();
            break;
          }
          case 18: {
            Opever = input.ReadString();
            break;
          }
          case 26: {
            Bomid = input.ReadString();
            break;
          }
          case 34: {
            Bomdsc = input.ReadString();
            break;
          }
          case 42: {
            Stageid = input.ReadString();
            break;
          }
          case 50: {
            Addtinfo1 = input.ReadString();
            break;
          }
          case 58: {
            Addtinfo2 = input.ReadString();
            break;
          }
          case 66: {
            Addtinfo3 = input.ReadString();
            break;
          }
          case 74: {
            Mtrlcnt = input.ReadString();
            break;
          }
          case 82: {
            oary2_.AddEntriesFrom(input, _repeated_oary2_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class APLPRDBMo_a2 : pb::IMessage<APLPRDBMo_a2> {
    private static readonly pb::MessageParser<APLPRDBMo_a2> _parser = new pb::MessageParser<APLPRDBMo_a2>(() => new APLPRDBMo_a2());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<APLPRDBMo_a2> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MqGrpcProject.APLPRDBMioReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APLPRDBMo_a2() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APLPRDBMo_a2(APLPRDBMo_a2 other) : this() {
      mtrlproductid_ = other.mtrlproductid_;
      mtrlproductdsc_ = other.mtrlproductdsc_;
      mtrlcate_ = other.mtrlcate_;
      planqty_ = other.planqty_;
      mtrlunit_ = other.mtrlunit_;
      spcfymtrllotid_ = other.spcfymtrllotid_;
      ext1_ = other.ext1_;
      ext2_ = other.ext2_;
      ext3_ = other.ext3_;
      ext4_ = other.ext4_;
      ext5_ = other.ext5_;
      parentid_ = other.parentid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APLPRDBMo_a2 Clone() {
      return new APLPRDBMo_a2(this);
    }

    /// <summary>Field number for the "mtrlproductid" field.</summary>
    public const int MtrlproductidFieldNumber = 1;
    private string mtrlproductid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mtrlproductid {
      get { return mtrlproductid_; }
      set {
        mtrlproductid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mtrlproductdsc" field.</summary>
    public const int MtrlproductdscFieldNumber = 2;
    private string mtrlproductdsc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mtrlproductdsc {
      get { return mtrlproductdsc_; }
      set {
        mtrlproductdsc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mtrlcate" field.</summary>
    public const int MtrlcateFieldNumber = 3;
    private string mtrlcate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mtrlcate {
      get { return mtrlcate_; }
      set {
        mtrlcate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "planqty" field.</summary>
    public const int PlanqtyFieldNumber = 4;
    private string planqty_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Planqty {
      get { return planqty_; }
      set {
        planqty_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mtrlunit" field.</summary>
    public const int MtrlunitFieldNumber = 5;
    private string mtrlunit_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mtrlunit {
      get { return mtrlunit_; }
      set {
        mtrlunit_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "spcfymtrllotid" field.</summary>
    public const int SpcfymtrllotidFieldNumber = 6;
    private string spcfymtrllotid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Spcfymtrllotid {
      get { return spcfymtrllotid_; }
      set {
        spcfymtrllotid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ext_1" field.</summary>
    public const int Ext1FieldNumber = 7;
    private string ext1_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Ext1 {
      get { return ext1_; }
      set {
        ext1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ext_2" field.</summary>
    public const int Ext2FieldNumber = 8;
    private string ext2_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Ext2 {
      get { return ext2_; }
      set {
        ext2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ext_3" field.</summary>
    public const int Ext3FieldNumber = 9;
    private string ext3_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Ext3 {
      get { return ext3_; }
      set {
        ext3_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ext_4" field.</summary>
    public const int Ext4FieldNumber = 10;
    private string ext4_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Ext4 {
      get { return ext4_; }
      set {
        ext4_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ext_5" field.</summary>
    public const int Ext5FieldNumber = 11;
    private string ext5_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Ext5 {
      get { return ext5_; }
      set {
        ext5_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "parentid" field.</summary>
    public const int ParentidFieldNumber = 12;
    private string parentid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Parentid {
      get { return parentid_; }
      set {
        parentid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as APLPRDBMo_a2);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(APLPRDBMo_a2 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Mtrlproductid != other.Mtrlproductid) return false;
      if (Mtrlproductdsc != other.Mtrlproductdsc) return false;
      if (Mtrlcate != other.Mtrlcate) return false;
      if (Planqty != other.Planqty) return false;
      if (Mtrlunit != other.Mtrlunit) return false;
      if (Spcfymtrllotid != other.Spcfymtrllotid) return false;
      if (Ext1 != other.Ext1) return false;
      if (Ext2 != other.Ext2) return false;
      if (Ext3 != other.Ext3) return false;
      if (Ext4 != other.Ext4) return false;
      if (Ext5 != other.Ext5) return false;
      if (Parentid != other.Parentid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Mtrlproductid.Length != 0) hash ^= Mtrlproductid.GetHashCode();
      if (Mtrlproductdsc.Length != 0) hash ^= Mtrlproductdsc.GetHashCode();
      if (Mtrlcate.Length != 0) hash ^= Mtrlcate.GetHashCode();
      if (Planqty.Length != 0) hash ^= Planqty.GetHashCode();
      if (Mtrlunit.Length != 0) hash ^= Mtrlunit.GetHashCode();
      if (Spcfymtrllotid.Length != 0) hash ^= Spcfymtrllotid.GetHashCode();
      if (Ext1.Length != 0) hash ^= Ext1.GetHashCode();
      if (Ext2.Length != 0) hash ^= Ext2.GetHashCode();
      if (Ext3.Length != 0) hash ^= Ext3.GetHashCode();
      if (Ext4.Length != 0) hash ^= Ext4.GetHashCode();
      if (Ext5.Length != 0) hash ^= Ext5.GetHashCode();
      if (Parentid.Length != 0) hash ^= Parentid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Mtrlproductid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Mtrlproductid);
      }
      if (Mtrlproductdsc.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Mtrlproductdsc);
      }
      if (Mtrlcate.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Mtrlcate);
      }
      if (Planqty.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Planqty);
      }
      if (Mtrlunit.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Mtrlunit);
      }
      if (Spcfymtrllotid.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Spcfymtrllotid);
      }
      if (Ext1.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Ext1);
      }
      if (Ext2.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Ext2);
      }
      if (Ext3.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Ext3);
      }
      if (Ext4.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Ext4);
      }
      if (Ext5.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Ext5);
      }
      if (Parentid.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Parentid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Mtrlproductid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mtrlproductid);
      }
      if (Mtrlproductdsc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mtrlproductdsc);
      }
      if (Mtrlcate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mtrlcate);
      }
      if (Planqty.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Planqty);
      }
      if (Mtrlunit.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mtrlunit);
      }
      if (Spcfymtrllotid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Spcfymtrllotid);
      }
      if (Ext1.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext1);
      }
      if (Ext2.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext2);
      }
      if (Ext3.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext3);
      }
      if (Ext4.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext4);
      }
      if (Ext5.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext5);
      }
      if (Parentid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Parentid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(APLPRDBMo_a2 other) {
      if (other == null) {
        return;
      }
      if (other.Mtrlproductid.Length != 0) {
        Mtrlproductid = other.Mtrlproductid;
      }
      if (other.Mtrlproductdsc.Length != 0) {
        Mtrlproductdsc = other.Mtrlproductdsc;
      }
      if (other.Mtrlcate.Length != 0) {
        Mtrlcate = other.Mtrlcate;
      }
      if (other.Planqty.Length != 0) {
        Planqty = other.Planqty;
      }
      if (other.Mtrlunit.Length != 0) {
        Mtrlunit = other.Mtrlunit;
      }
      if (other.Spcfymtrllotid.Length != 0) {
        Spcfymtrllotid = other.Spcfymtrllotid;
      }
      if (other.Ext1.Length != 0) {
        Ext1 = other.Ext1;
      }
      if (other.Ext2.Length != 0) {
        Ext2 = other.Ext2;
      }
      if (other.Ext3.Length != 0) {
        Ext3 = other.Ext3;
      }
      if (other.Ext4.Length != 0) {
        Ext4 = other.Ext4;
      }
      if (other.Ext5.Length != 0) {
        Ext5 = other.Ext5;
      }
      if (other.Parentid.Length != 0) {
        Parentid = other.Parentid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Mtrlproductid = input.ReadString();
            break;
          }
          case 18: {
            Mtrlproductdsc = input.ReadString();
            break;
          }
          case 26: {
            Mtrlcate = input.ReadString();
            break;
          }
          case 34: {
            Planqty = input.ReadString();
            break;
          }
          case 42: {
            Mtrlunit = input.ReadString();
            break;
          }
          case 50: {
            Spcfymtrllotid = input.ReadString();
            break;
          }
          case 58: {
            Ext1 = input.ReadString();
            break;
          }
          case 66: {
            Ext2 = input.ReadString();
            break;
          }
          case 74: {
            Ext3 = input.ReadString();
            break;
          }
          case 82: {
            Ext4 = input.ReadString();
            break;
          }
          case 90: {
            Ext5 = input.ReadString();
            break;
          }
          case 98: {
            Parentid = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class APLPRDBMo_a : pb::IMessage<APLPRDBMo_a> {
    private static readonly pb::MessageParser<APLPRDBMo_a> _parser = new pb::MessageParser<APLPRDBMo_a>(() => new APLPRDBMo_a());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<APLPRDBMo_a> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MqGrpcProject.APLPRDBMioReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APLPRDBMo_a() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APLPRDBMo_a(APLPRDBMo_a other) : this() {
      sname_ = other.sname_;
      svalue_ = other.svalue_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APLPRDBMo_a Clone() {
      return new APLPRDBMo_a(this);
    }

    /// <summary>Field number for the "sname" field.</summary>
    public const int SnameFieldNumber = 1;
    private string sname_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Sname {
      get { return sname_; }
      set {
        sname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "svalue" field.</summary>
    public const int SvalueFieldNumber = 2;
    private string svalue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Svalue {
      get { return svalue_; }
      set {
        svalue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as APLPRDBMo_a);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(APLPRDBMo_a other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Sname != other.Sname) return false;
      if (Svalue != other.Svalue) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Sname.Length != 0) hash ^= Sname.GetHashCode();
      if (Svalue.Length != 0) hash ^= Svalue.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Sname.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Sname);
      }
      if (Svalue.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Svalue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Sname.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sname);
      }
      if (Svalue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Svalue);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(APLPRDBMo_a other) {
      if (other == null) {
        return;
      }
      if (other.Sname.Length != 0) {
        Sname = other.Sname;
      }
      if (other.Svalue.Length != 0) {
        Svalue = other.Svalue;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Sname = input.ReadString();
            break;
          }
          case 18: {
            Svalue = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
