// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MqGrpcProject.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MqGrpcProject {

  /// <summary>Holder for reflection information generated from MqGrpcProject.proto</summary>
  public static partial class MqGrpcProjectReflection {

    #region Descriptor
    /// <summary>File descriptor for MqGrpcProject.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MqGrpcProjectReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNNcUdycGNQcm9qZWN0LnByb3RvEg1NcUdycGNQcm9qZWN0GhBBUENNVExT",
            "VGlvLnByb3RvGhBBUElNVExTVGlvLnByb3RvGhBBUElTSFRFUWlvLnByb3Rv",
            "GhBBUExQUkRCTWlvLnByb3RvGhBBUExSU1ZQUmlvLnByb3RvGhBBUE1FUVJT",
            "VmlvLnByb3RvMvsDCgdNcUdycGNzElEKDUFQQ01UTFNUX1NlbmQSHy5NcUdy",
            "cGNQcm9qZWN0LkFQQ01UTFNUX1JlcXVlc3QaHS5NcUdycGNQcm9qZWN0LkFQ",
            "Q01UTFNUX1JlcGx5IgASUQoNQVBNRVFSU1ZfU2VuZBIfLk1xR3JwY1Byb2pl",
            "Y3QuQVBNRVFSU1ZfUmVxdWVzdBodLk1xR3JwY1Byb2plY3QuQVBNRVFSU1Zf",
            "UmVwbHkiABJRCg1BUElNVExTVF9TZW5kEh8uTXFHcnBjUHJvamVjdC5BUElN",
            "VExTVF9SZXF1ZXN0Gh0uTXFHcnBjUHJvamVjdC5BUElNVExTVF9SZXBseSIA",
            "ElEKDUFQSVNIVEVRX1NlbmQSHy5NcUdycGNQcm9qZWN0LkFQSVNIVEVRX1Jl",
            "cXVlc3QaHS5NcUdycGNQcm9qZWN0LkFQSVNIVEVRX1JlcGx5IgASUQoNQVBM",
            "UFJEQk1fU2VuZBIfLk1xR3JwY1Byb2plY3QuQVBMUFJEQk1fUmVxdWVzdBod",
            "Lk1xR3JwY1Byb2plY3QuQVBMUFJEQk1fUmVwbHkiABJRCg1BUExSU1ZQUl9T",
            "ZW5kEh8uTXFHcnBjUHJvamVjdC5BUExSU1ZQUl9SZXF1ZXN0Gh0uTXFHcnBj",
            "UHJvamVjdC5BUExSU1ZQUl9SZXBseSIAQjMKFWlvLmdycGMuTXFHcnBjUHJv",
            "amVjdEISTXFHcnBjUHJvamVjdFByb3RvUAGiAgNITFdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MqGrpcProject.APCMTLSTioReflection.Descriptor, global::MqGrpcProject.APIMTLSTioReflection.Descriptor, global::MqGrpcProject.APISHTEQioReflection.Descriptor, global::MqGrpcProject.APLPRDBMioReflection.Descriptor, global::MqGrpcProject.APLRSVPRioReflection.Descriptor, global::MqGrpcProject.APMEQRSVioReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
